name: create a pull request
on:
    push:
        branches:
            - '*'
jobs:
    create-pull-request:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                  commit-message: push request
                  title: push request
                  body: push
